import type { EvidenceRecord, Provenance, ReviewAction, WorkflowCanvasV1 } from './types';

const provenance = (sourceId: string, producerLabel: string): Provenance => ({
  kind: 'runner-record',
  sourceId,
  createdAt: '2026-08-20T16:00:00.000Z',
  producerLabel,
});

const nextReview = (
  id: string,
  label: string,
  surface: Extract<ReviewAction, { kind: 'navigate' }>['destination']['surface'],
  entityId?: string
): ReviewAction => ({
  kind: 'navigate',
  id,
  label,
  href: `/workflow-review/${id}`,
  destination: { surface, workflowId: 'privacy-safe-onboarding', entityId },
});

const binding = (
  stepId: string,
  checkpointId: string,
  platform: string
): EvidenceRecord['binding'] => ({
  workflowId: 'privacy-safe-onboarding',
  workflowRevisionId: 'revision-demo-7',
  stepId,
  checkpointId,
  platform,
});

export const workflowCanvasV1Fixture: WorkflowCanvasV1 = {
  schemaVersion: 'workflow-canvas/v1',
  documentId: 'canvas-demo-run-17',
  generatedAt: '2026-08-20T16:05:00.000Z',
  context: { kind: 'run', runId: 'run-demo-17' },
  workflow: {
    id: 'privacy-safe-onboarding',
    label: 'Privacy-safe onboarding review',
    revisionId: 'revision-demo-7',
    phase: { code: 'review', label: 'Review', tone: 'info' },
  },
  decision: {
    state: 'incomplete',
    label: 'Review incomplete',
    reason: 'The producer supplied one open finding and one unavailable observation.',
    nextReview: nextReview('open-findings', 'Review supplied findings', 'findings'),
  },
  nodes: [
    {
      id: 'welcome',
      order: 0,
      label: 'Welcome',
      action: 'Open the welcome surface.',
      expectedOutcomes: ['The introduction is visible.', 'The continue action is available.'],
      dependencyIds: [],
      checkpointIds: ['welcome-ready'],
      decision: {
        state: 'clean',
        label: 'Observed',
        reason: 'The supplied observation matches the reviewed reference.',
        nextReview: { kind: 'none', reason: 'No further review was supplied.' },
      },
      platformStates: [
        { platform: 'desktop', status: { code: 'observed', label: 'Observed', tone: 'success' } },
      ],
      referenceEvidenceIds: ['welcome-reference'],
      observationEvidenceIds: ['welcome-observation'],
      resolutionEvidenceIds: [],
      findingIds: [],
      comparisonIds: ['welcome-comparison'],
    },
    {
      id: 'profile',
      order: 1,
      label: 'Profile details',
      action: 'Enter the example profile fields.',
      expectedOutcomes: [
        'All required fields remain labelled.',
        'The continue action remains available.',
      ],
      dependencyIds: ['welcome'],
      checkpointIds: ['profile-complete'],
      decision: {
        state: 'failed',
        label: 'Finding supplied',
        reason: 'The producer supplied a contrast finding for the mobile observation.',
        nextReview: nextReview(
          'finding-demo-1',
          'Inspect finding',
          'finding-detail',
          'finding-demo-1'
        ),
      },
      platformStates: [
        { platform: 'desktop', status: { code: 'reviewed', label: 'Reviewed', tone: 'success' } },
        {
          platform: 'mobile',
          status: { code: 'finding-open', label: 'Finding open', tone: 'danger' },
        },
      ],
      referenceEvidenceIds: ['profile-reference'],
      observationEvidenceIds: ['profile-observation'],
      resolutionEvidenceIds: ['profile-resolution'],
      findingIds: ['finding-demo-1'],
      comparisonIds: ['profile-comparison'],
    },
    {
      id: 'confirmation',
      order: 2,
      label: 'Confirmation',
      action: 'Review the confirmation surface.',
      expectedOutcomes: ['A confirmation summary is available.'],
      dependencyIds: ['profile'],
      checkpointIds: ['confirmation-visible'],
      decision: {
        state: 'unavailable',
        label: 'Observation unavailable',
        reason: 'The producer reported that the exact run observation is unavailable.',
        nextReview: nextReview('run-demo-17', 'Open run detail', 'run-detail', 'run-demo-17'),
      },
      platformStates: [
        {
          platform: 'mobile',
          status: { code: 'unavailable', label: 'Unavailable', tone: 'warning' },
        },
      ],
      referenceEvidenceIds: [],
      observationEvidenceIds: ['confirmation-observation'],
      resolutionEvidenceIds: [],
      findingIds: [],
      comparisonIds: [],
    },
  ],
  edges: [
    { id: 'welcome-profile', fromNodeId: 'welcome', toNodeId: 'profile', label: 'Continue' },
    {
      id: 'profile-confirmation',
      fromNodeId: 'profile',
      toNodeId: 'confirmation',
      label: 'Submit',
    },
  ],
  evidence: [
    {
      id: 'welcome-reference',
      role: 'reference',
      label: 'Welcome reference',
      availability: 'available',
      integrity: { state: 'verified', algorithm: 'sha256', digest: 'demo-welcome-reference' },
      binding: binding('welcome', 'welcome-ready', 'desktop'),
      dimensions: { width: 1672, height: 941 },
      asset: {
        url: '/workflow-fixtures/welcome-reference.webp',
        thumbnailUrl: '/workflow-fixtures/welcome-reference-thumb.webp',
        mediaType: 'image/webp',
        renderPolicy: 'thumbnail-and-detail',
      },
      referenceSelection: {
        status: 'eligible',
        authority: 'operator-approval',
        selectionId: 'selection-welcome',
        selectedAt: '2026-08-19T12:00:00.000Z',
        policyId: 'policy-demo',
        supervisedTraining: true,
        runCompleted: true,
        trainingPassed: true,
        approval: 'accepted',
        workflowRevisionMatch: true,
        stepCheckpointPlatformMatch: true,
        integrityVerified: true,
        currentByPolicy: true,
        reasons: [],
        primaryForNodePlatform: true,
      },
      provenance: provenance('reference-welcome', 'Approved reference record'),
    },
    {
      id: 'welcome-observation',
      role: 'observation',
      label: 'Welcome run observation',
      availability: 'available',
      integrity: { state: 'verified', algorithm: 'sha256', digest: 'demo-welcome-observation' },
      binding: { ...binding('welcome', 'welcome-ready', 'desktop'), runId: 'run-demo-17' },
      observedAt: '2026-08-20T15:00:00.000Z',
      dimensions: { width: 1672, height: 941 },
      asset: {
        url: '/workflow-fixtures/welcome-observation.webp',
        mediaType: 'image/webp',
        renderPolicy: 'thumbnail-and-detail',
      },
      provenance: provenance('run-demo-17-welcome', 'Runner observation'),
    },
    {
      id: 'profile-reference',
      role: 'reference',
      label: 'Profile reference',
      availability: 'stale',
      availabilityReason: 'The producer marked this selection stale by policy.',
      integrity: { state: 'verified', algorithm: 'sha256', digest: 'demo-profile-reference' },
      binding: binding('profile', 'profile-complete', 'mobile'),
      dimensions: { width: 1672, height: 941 },
      asset: {
        url: '/workflow-fixtures/profile-reference.webp',
        mediaType: 'image/webp',
        renderPolicy: 'thumbnail-and-detail',
      },
      referenceSelection: {
        status: 'ineligible',
        authority: 'runner-policy',
        selectionId: 'selection-profile',
        selectedAt: '2026-08-01T12:00:00.000Z',
        policyId: 'policy-demo',
        supervisedTraining: true,
        runCompleted: true,
        trainingPassed: true,
        approval: 'not-required',
        workflowRevisionMatch: true,
        stepCheckpointPlatformMatch: true,
        integrityVerified: true,
        currentByPolicy: false,
        reasons: ['stale-by-policy'],
        primaryForNodePlatform: false,
      },
      provenance: provenance('reference-profile', 'Policy-selected reference record'),
    },
    {
      id: 'profile-observation',
      role: 'observation',
      label: 'Profile mobile observation',
      availability: 'available',
      integrity: { state: 'verified', algorithm: 'sha256', digest: 'demo-profile-observation' },
      binding: { ...binding('profile', 'profile-complete', 'mobile'), runId: 'run-demo-17' },
      observedAt: '2026-08-20T15:02:00.000Z',
      dimensions: { width: 1672, height: 941 },
      asset: {
        url: '/workflow-fixtures/profile-observation.webp',
        mediaType: 'image/webp',
        renderPolicy: 'thumbnail-and-detail',
      },
      provenance: provenance('run-demo-17-profile', 'Runner observation'),
    },
    {
      id: 'profile-resolution',
      role: 'resolution',
      label: 'Profile proposed resolution',
      availability: 'available',
      integrity: { state: 'verified', algorithm: 'sha256', digest: 'demo-profile-resolution' },
      binding: {
        ...binding('profile', 'profile-complete', 'mobile'),
        findingId: 'finding-demo-1',
        resolutionId: 'resolution-demo-1',
      },
      dimensions: { width: 1672, height: 941 },
      asset: {
        url: '/workflow-fixtures/profile-resolution.webp',
        mediaType: 'image/webp',
        renderPolicy: 'thumbnail-and-detail',
      },
      provenance: {
        ...provenance('resolution-demo-1', 'Resolution journal'),
        kind: 'resolution-journal',
      },
    },
    {
      id: 'confirmation-observation',
      role: 'observation',
      label: 'Confirmation observation',
      availability: 'unavailable',
      availabilityReason: 'The exact run ended before this checkpoint was captured.',
      integrity: { state: 'not-applicable' },
      binding: {
        ...binding('confirmation', 'confirmation-visible', 'mobile'),
        runId: 'run-demo-17',
      },
      provenance: provenance('run-demo-17-confirmation', 'Runner observation state'),
    },
  ],
  findings: [
    {
      id: 'finding-demo-1',
      nodeId: 'profile',
      label: 'Mobile contrast',
      summary: 'The producer reported insufficient contrast for the supplied mobile observation.',
      status: { code: 'open', label: 'Open', tone: 'danger' },
      evidenceIds: ['profile-observation'],
      nextReview: nextReview(
        'finding-demo-1',
        'Open finding detail',
        'finding-detail',
        'finding-demo-1'
      ),
      provenance: { ...provenance('finding-demo-1', 'Finding journal'), kind: 'finding-journal' },
    },
  ],
  annotations: [
    {
      id: 'annotation-demo-1',
      kind: 'finding-region',
      targetEvidenceId: 'profile-observation',
      geometry: { x: 0.12, y: 0.62, width: 0.56, height: 0.12 },
      content: 'Producer-supplied finding region',
      provenance: { ...provenance('finding-demo-1', 'Finding overlay'), kind: 'derived-overlay' },
      integrity: { state: 'verified', algorithm: 'sha256', digest: 'demo-annotation' },
    },
  ],
  comparisons: [
    {
      id: 'welcome-comparison',
      kind: 'evaluation',
      label: 'Welcome evaluation',
      summary: 'Producer-supplied evaluation comparison.',
      status: { code: 'reviewed', label: 'Reviewed', tone: 'success' },
      left: { evidenceId: 'welcome-reference', label: 'Reference', role: 'reference' },
      right: { evidenceId: 'welcome-observation', label: 'Observation', role: 'observation' },
      dimensionResults: [
        {
          id: 'content',
          label: 'Content',
          status: { code: 'reviewed', label: 'Reviewed', tone: 'success' },
          summary: 'The producer supplied no content finding.',
        },
      ],
      nextReview: { kind: 'none', reason: 'No further comparison review was supplied.' },
    },
    {
      id: 'profile-comparison',
      kind: 'resolution',
      label: 'Profile resolution review',
      summary: 'Producer-supplied observation and resolution comparison.',
      status: { code: 'finding-open', label: 'Finding open', tone: 'warning' },
      left: { evidenceId: 'profile-observation', label: 'Observation', role: 'observation' },
      right: { evidenceId: 'profile-resolution', label: 'Resolution', role: 'resolution' },
      dimensionResults: [
        {
          id: 'contrast',
          label: 'Contrast',
          status: { code: 'pending-review', label: 'Pending review', tone: 'warning' },
          summary: 'The supplied resolution still requires review.',
        },
      ],
      nextReview: nextReview(
        'resolution-demo-1',
        'Review resolution',
        'resolution-detail',
        'resolution-demo-1'
      ),
    },
  ],
};
